### ISSUE TITLE
Docker部署后，前端页面使用报错

### ISSUE THREAD

**Issue by tianxiuali** [unit-mesh/chocolate-factory#10]
1. 本地执行 `docker-compose up`
2. 浏览器访问 http://localhost:3000/

控制台报错，报错接口：http://localhost:3000/api/workflows/frontend

![image](https://github.com/unit-mesh/chocolate-factory/assets/17540361/5a2859d7-94f5-467f-ac77-07e9ffec3591)

选择示例“商品订单详细”，点击发送报错，报错接口：http://localhost:3000/api/chat

![image](https://github.com/unit-mesh/chocolate-factory/assets/17540361/3a9efd6a-bef1-43df-81e3-efe2017a7c51)

![image](https://github.com/unit-mesh/chocolate-factory/assets/17540361/439f9393-54bd-4786-97ad-ef7233d76278)

![image](https://github.com/unit-mesh/chocolate-factory/assets/17540361/0eaaeab6-94ab-4d7e-bda5-717a104e9c8f)

如果通过Postman直接调用 http://localhost:18080/api/chat ，在Docker看到以下错误信息：

![image](https://github.com/unit-mesh/chocolate-factory/assets/17540361/3649b3f3-cf58-423c-89e3-6c6258a8d241)

**Comment by phodal** [comment]
别的功能正常吗？如果别的功能正常的话，就是模型没有按预期返回

**Comment by tianxiuali** [comment]
别的功能是指？我看 Chocolate Factory 就只有聊天功能

**Comment by phodal** [comment]
Frontend 那里可以选择。如果你的容器网络可以直接连 OpenAI  的服务器，别的功能应该也 OK

**Comment by tianxiuali** [comment]
都不行呀😂

**Comment by phodal** [comment]
太惨了，server  只要是提供  demo 用的，OpenAI  受网络影响比较大

**Comment by phodal** [comment]
从报错信息和代码来看，大概率是网络有问题：

https://github.com/unit-mesh/chocolate-factory/blob/54490c674b82ee05fd9dd5233b4d47d2b512e398/cocoa-core/src/main/kotlin/cc/unitmesh/cf/core/flow/model/FlowActionFlag.kt#L28-L32

**Comment by tianxiuali** [comment]
OK了，确实是网络的问题😂谢谢啦！
