### ISSUE TITLE
运行不了，es报错

### ISSUE THREAD

**Issue by rootcax** [unit-mesh/chocolate-factory#4]
zzz@10:~/chocolate-factory$ id

uid=1000(zzz) gid=1000(zzz) groups=1000(zzz),996(docker),998(vboxsf)

zzz@10:~/chocolate-factory$ ls

build.gradle.kts  docker-compose.yml  gradlew      plugins

CHANGELOG.md      Dockerfile          gradlew.bat  rag-modules

choc-ui           docs                LICENSE      README.md

client            docs-builder        llm-modules  server

CNAME             dsl                 llm-tools    settings.gradle.kts

cocoa-core        examples            logs

code              _fixtures           nginx

data              gradle              packages

zzz@10:~/chocolate-factory$ uname -a

Linux 10 5.10.0-23-amd64 #1 SMP Debian 5.10.179-2 (2023-07-14) x86_64 GNU/Linux

zzz@10:~/chocolate-factory$ docker-compose up

Starting elasticsearch ... done

Starting backend       ... done

Starting frontend      ... done

Starting nginx         ... done

Attaching to backend, elasticsearch, frontend, nginx

nginx            | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration

nginx            | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/

nginx            | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh

nginx            | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf

nginx            | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version

nginx            | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh

nginx            | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh

nginx            | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh

nginx            | /docker-entrypoint.sh: Configuration complete; ready for start up

nginx            | 2023/10/10 02:01:39 [notice] 1#1: using the "epoll" event method

nginx            | 2023/10/10 02:01:39 [notice] 1#1: nginx/1.25.2

nginx            | 2023/10/10 02:01:39 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r10) 

nginx            | 2023/10/10 02:01:39 [notice] 1#1: OS: Linux 5.10.0-23-amd64

nginx            | 2023/10/10 02:01:39 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576

nginx            | 2023/10/10 02:01:39 [notice] 1#1: start worker processes

nginx            | 2023/10/10 02:01:39 [notice] 1#1: start worker process 30

nginx            | 2023/10/10 02:01:39 [notice] 1#1: start worker process 31

nginx            | 2023/10/10 02:01:39 [notice] 1#1: start worker process 32

nginx            | 2023/10/10 02:01:39 [notice] 1#1: start cache manager process 33

nginx            | 2023/10/10 02:01:39 [notice] 1#1: start cache loader process 34

^CGracefully stopping... (press Ctrl+C again to force)

Stopping nginx         ... done

Stopping frontend      ... done

Stopping backend       ... done

Stopping elasticsearch ... done

zzz@10:~/chocolate-factory$ docker-compose up

Starting elasticsearch ... done

Starting backend       ... done

Starting frontend      ... done

Starting nginx         ... done

Attaching to elasticsearch, backend, frontend, nginx

nginx            | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration

nginx            | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/

nginx            | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh

nginx            | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf

nginx            | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version

nginx            | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh

nginx            | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh

nginx            | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh

nginx            | /docker-entrypoint.sh: Configuration complete; ready for start up

nginx            | 2023/10/10 02:01:51 [notice] 1#1: using the "epoll" event method

nginx            | 2023/10/10 02:01:51 [notice] 1#1: nginx/1.25.2

nginx            | 2023/10/10 02:01:51 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r10) 

nginx            | 2023/10/10 02:01:51 [notice] 1#1: OS: Linux 5.10.0-23-amd64

nginx            | 2023/10/10 02:01:51 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576

nginx            | 2023/10/10 02:01:51 [notice] 1#1: start worker processes

nginx            | 2023/10/10 02:01:51 [notice] 1#1: start worker process 29

nginx            | 2023/10/10 02:01:51 [notice] 1#1: start worker process 30

nginx            | 2023/10/10 02:01:51 [notice] 1#1: start worker process 31

nginx            | 2023/10/10 02:01:51 [notice] 1#1: start cache manager process 32

nginx            | 2023/10/10 02:01:51 [notice] 1#1: start cache loader process 33

frontend         | Listening on port 3000 url: http://0.0.0.0:3000

elasticsearch    | Exception in thread "main" java.lang.RuntimeException: starting java failed with [1]

elasticsearch    | output:

elasticsearch    | [0.000s][error][logging] Error opening log file 'logs/gc.log': Permission denied

elasticsearch    | [0.000s][error][logging] Initialization of output 'file=logs/gc.log' using options 'filecount=32,filesize=64m' failed.

elasticsearch    | error:

elasticsearch    | Invalid -Xlog option '-Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m', see error log for details.

elasticsearch    | Error: Could not create the Java Virtual Machine.

elasticsearch    | Error: A fatal exception has occurred. Program will exit.

elasticsearch    | 	at org.elasticsearch.tools.launchers.JvmOption.flagsFinal(JvmOption.java:119)

elasticsearch    | 	at org.elasticsearch.tools.launchers.JvmOption.findFinalOptions(JvmOption.java:81)

elasticsearch    | 	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:38)

elasticsearch    | 	at org.elasticsearch.tools.launchers.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:135)

elasticsearch    | 	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:86)

^CGracefully stopping... (press Ctrl+C again to force)

Stopping nginx         ... done

Stopping frontend      ... done

Stopping backend       ... done

Stopping elasticsearch ... done

**Comment by phodal** [comment]
参考一下 [docker-compose.yml](https://github.com/unit-mesh/chocolate-factory/blob/master/docker-compose.yml)  的持久化配置，需要分别创建 data,logs,plugins 三个目录用来挂载：

```
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./logs:/usr/share/elasticsearch/logs
      - ./plugins:/usr/share/elasticsearch/plugins
```

即将 `/usr/share/elasticsearch/data` 改为你对应的宿主机host文件目录

**Comment by rootcax** [comment]
> elasticsearch

好的，谢谢
