### ISSUE TITLE
18080端口连接不了

### ISSUE THREAD

**Issue by rootcax** [unit-mesh/chocolate-factory#5]
tcp        0      0 0.0.0.0:18080           0.0.0.0:*               LISTEN     

tcp6       0      0 :::18080                :::*                    LISTEN     

jojo@10:~/chocolate-factory$ 

启动后端口是监听状态的，但是发送问题，显示xx，backend提示错误

frontend         | Failed to proxy http://localhost:18080/api/workflows/frontend Error: connect ECONNREFUSED 127.0.0.1:18080

frontend         |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {

frontend         |   errno: -111,

frontend         |   code: 'ECONNREFUSED',

frontend         |   syscall: 'connect',

frontend         |   address: '127.0.0.1',

frontend         |   port: 18080

frontend         | }

**Comment by phodal** [comment]
信息太少，无法 debug，你需要自己看一下日志中哪里出错了
