### ISSUE TITLE
该AI  Agent能帮助做DDD设计吗，比如给一个需求，让它输出统一语言、做事件风暴、聚合、BC、以及设计到代码的自动生成等

### ISSUE THREAD

**Issue by smilucky** [unit-mesh/chocolate-factory#6]

**Comment by phodal** [comment]
理论上是可以的，但是需要你自己去设计

**Comment by smilucky** [comment]
但是文档中好像很少描述怎么使用该工具以及基于它怎么做定制或扩展

**Comment by phodal** [comment]
有的：

脚手架：https://github.com/unit-mesh/chocolate-factory-examples

开发新的 Workflow：https://framework.unitmesh.cc/workflow/workflow-development.html

如何设计 prompt 来关联：https://framework.unitmesh.cc/prompt/frontend/frontend-overview.html

更详细的只能看代码了
